version: '2'
services:
  ssh:
    build: .
    privileged: true
    environment:
      - "SSH_PORT=${SSH_PORT}"
      - "USERS=${USERS}"
    ports:
     - "${SSH_PORT}:${SSH_PORT}/tcp"
    volumes:
     - /sys/fs/cgroup:/sys/fs/cgroup:ro
     - /etc/ssh:/srv/secrets/ssh:ro
     - /home:/home:rw
     - /srv:/srv:rw
